# Generated by Django 2.0.1 on 2018-01-12 21:26

from django.db import migrations, models
import topic.models.model


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='icon_path',
            field=models.FileField(upload_to=topic.models.model.upload_to_area, verbose_name='图标路径'),
        ),
    ]
