# Generated by Django 2.0.1 on 2018-01-12 22:09

from django.db import migrations, models
import topic.models.model


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0003_auto_20180112_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='icon_path',
            field=models.ImageField(height_field=100, upload_to=topic.models.model.upload_to_area, verbose_name='图标路径', width_field=100),
        ),
    ]
