# Generated by Django 2.0.1 on 2018-01-13 14:38

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0005_auto_20180112_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='content',
            field=tinymce.models.HTMLField(blank=True, verbose_name='话题内容'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='user',
            field=models.ForeignKey(default='admin', on_delete=django.db.models.deletion.CASCADE, to='user.User', to_field='user', verbose_name='用户'),
        ),
    ]
