# Generated by Django 2.0.1 on 2018-01-13 15:32

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0006_auto_20180113_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='content',
            field=tinymce.models.HTMLField(verbose_name='话题内容'),
        ),
    ]
