# Generated by Django 2.0.1 on 2018-01-14 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0007_auto_20180113_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='path_name',
            field=models.CharField(default='nono', max_length=10, verbose_name='url路径名'),
            preserve_default=False,
        ),
    ]
