# Generated by Django 2.0.1 on 2018-01-14 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0008_area_path_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='status',
            field=models.BooleanField(default=True, verbose_name='审核状态'),
        ),
    ]
