# Generated by Django 2.0.1 on 2018-01-17 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0009_auto_20180114_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='name',
            field=models.CharField(max_length=10, unique=True, verbose_name='分区名'),
        ),
        migrations.AlterField(
            model_name='area',
            name='path_name',
            field=models.CharField(max_length=10, unique=True, verbose_name='url路径名'),
        ),
    ]
