# Generated by Django 2.0.1 on 2018-01-19 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0010_auto_20180117_1144'),
    ]

    operations = [
        migrations.CreateModel(
            name='TouristsComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_obj', models.IntegerField(verbose_name='回复对象数据库id')),
                ('content', models.CharField(max_length=200, verbose_name='评论内容')),
                ('ip', models.CharField(max_length=48, verbose_name='游客ip')),
                ('topic_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incognito_comment', to='topic.Topic', verbose_name='话题')),
            ],
        ),
        migrations.RemoveField(
            model_name='incognitocomment',
            name='comment_obj',
        ),
        migrations.RemoveField(
            model_name='incognitocomment',
            name='topic_id',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='floor',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='with_floor',
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_obj',
            field=models.IntegerField(verbose_name='回复对象数据库id'),
        ),
        migrations.DeleteModel(
            name='IncognitoComment',
        ),
    ]
