# Generated by Django 2.0.1 on 2018-01-19 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0011_auto_20180119_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_obj',
            field=models.IntegerField(null=True, verbose_name='回复对象数据库id'),
        ),
    ]
