# Generated by Django 2.0.1 on 2018-01-19 13:28

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0013_comment_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=tinymce.models.HTMLField(verbose_name='评论内容'),
        ),
    ]
