# Generated by Django 2.0.1 on 2018-01-20 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0014_auto_20180119_1328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='incognito',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='incognito',
        ),
    ]
