# Generated by Django 2.0.1 on 2018-01-20 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0016_auto_20180120_1136'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment_obj',
            new_name='reply_obj',
        ),
    ]
