# Generated by Django 2.0.1 on 2018-01-20 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0017_auto_20180120_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='reply_obj',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply', to='topic.Comment', verbose_name='回复对象'),
        ),
    ]
