# Generated by Django 2.0.1 on 2018-01-21 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20180114_2141'),
        ('topic', '0018_auto_20180120_1527'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='topic.Topic', verbose_name='话题')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='user.User', to_field='user', verbose_name='用户')),
            ],
        ),
    ]
