# Generated by Django 2.0.1 on 2018-01-22 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20180114_2141'),
        ('topic', '0019_collection'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentLOC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(verbose_name='赞或反对')),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='LOC', to='topic.Comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentLOC', to='user.User', to_field='user')),
            ],
        ),
    ]
