# Generated by Django 2.0.1 on 2018-01-22 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0020_commentloc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentloc',
            name='status',
            field=models.NullBooleanField(verbose_name='赞或反对'),
        ),
    ]
