# Generated by Django 2.0.1 on 2018-01-22 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20180114_2141'),
        ('topic', '0021_auto_20180122_1109'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LikeOrContra',
            new_name='TopicLOC',
        ),
    ]
