# Generated by Django 2.0.1 on 2018-01-27 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0023_auto_20180123_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='description',
            field=models.TextField(null=True, verbose_name='描述'),
        ),
        migrations.AddField(
            model_name='tag',
            name='icon',
            field=models.FileField(null=True, upload_to='status/img/tag_icon/', verbose_name='图标'),
        ),
    ]
