# Generated by Django 2.0.1 on 2018-01-28 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0025_auto_20180128_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='audit_message',
            field=models.CharField(default=' ', max_length=50, verbose_name='审核留言'),
            preserve_default=False,
        )
    ]
