# Generated by Django 2.0.1 on 2018-01-28 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0026_auto_20180128_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='audit_message',
            field=models.CharField(max_length=50, null=True, verbose_name='审核留言'),
        ),
    ]
