# Generated by Django 2.0.1 on 2018-01-28 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0027_auto_20180128_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.BooleanField(default=True, verbose_name='审核状态'),
        ),
    ]
