# Generated by Django 2.0.1 on 2018-01-29 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0028_auto_20180128_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='status',
            field=models.BooleanField(default=False, verbose_name='状态'),
        ),
    ]
