# Generated by Django 2.0.1 on 2018-01-30 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0030_auto_20180130_1305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='audit_message',
        ),
    ]
