# Generated by Django 2.0.1 on 2018-01-12 15:08

from django.db import migrations, models
import django.db.models.deletion
import user.models.model


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cookie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(max_length=48, verbose_name='cookie_sid')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='Defense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_ip', models.CharField(max_length=48, verbose_name='ip地址')),
                ('func_name', models.CharField(max_length=48, verbose_name='函数名')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_time', models.DateTimeField(auto_now=True, verbose_name='最后记录时间')),
                ('interval', models.IntegerField(default=1, verbose_name='间隔时间,秒数')),
                ('frequency', models.IntegerField(default=0, verbose_name='记录次数')),
                ('status', models.BooleanField(default=True, verbose_name='状态')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20, unique=True, verbose_name='帐号名')),
                ('nickname', models.CharField(max_length=20, unique=True, verbose_name='昵称')),
                ('password', models.CharField(max_length=48, verbose_name='密码')),
                ('avatar', models.FileField(default='/static/img/default_avatar.jpg', upload_to=user.models.model.upload_to, verbose_name='用户头像')),
                ('level', models.IntegerField(default=0, verbose_name='权限等级')),
                ('email', models.EmailField(max_length=50, null=True, unique=True, verbose_name='邮箱')),
                ('phone', models.CharField(max_length=12, verbose_name='手机号')),
                ('attention', models.IntegerField(default=0, verbose_name='关注人数')),
                ('fans', models.IntegerField(default=0, verbose_name='被关注人数')),
                ('integral', models.IntegerField(default=10, verbose_name='积分')),
                ('status', models.BooleanField(default=False, verbose_name='激活状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
                ('login_time', models.DateTimeField(auto_now=True, verbose_name='登录时间')),
            ],
        ),
        migrations.AddField(
            model_name='cookie',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cookie_sid', to='user.User', to_field='user', verbose_name='user'),
        ),
    ]
