# Generated by Django 2.0.1 on 2018-01-30 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20180114_2141'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200, verbose_name='消息内容')),
                ('types', models.CharField(max_length=10, unique=True, verbose_name='消息类型')),
                ('status', models.BooleanField(default=False, verbose_name='阅读状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='m_to_user', to='user.User', to_field='user', verbose_name='接收人')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='m_user', to='user.User', to_field='user', verbose_name='发送人')),
            ],
        ),
    ]
