# Generated by Django 2.0.1 on 2018-01-30 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_message_types_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='types',
            field=models.CharField(max_length=10, verbose_name='消息类型'),
        ),
    ]
