# Generated by Django 2.0.1 on 2018-01-30 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20180130_1404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='attention',
        ),
        migrations.RemoveField(
            model_name='user',
            name='fans',
        ),
    ]
