# Generated by Django 2.0.1 on 2018-02-01 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20180130_1517'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blacklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='b_to_user', to='user.User', to_field='user', verbose_name='被拉黑用户')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='b_user', to='user.User', to_field='user', verbose_name='用户')),
            ],
        ),
    ]
