# Generated by Django 2.0.1 on 2018-02-06 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20180201_1612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='to_user',
        ),
        migrations.AddField(
            model_name='message',
            name='addressee',
            field=models.ForeignKey(default='neo', on_delete=django.db.models.deletion.CASCADE, related_name='m_addressee', to='user.User', to_field='user', verbose_name='信息接收方'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(default='neo', on_delete=django.db.models.deletion.CASCADE, related_name='m_sender', to='user.User', to_field='user', verbose_name='信息发送方'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='m_user', to='user.User', to_field='user', verbose_name='用户'),
        ),
    ]
