# Generated by Django 2.0.1 on 2018-02-06 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20180206_1408'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='user_status',
            new_name='delete_status',
        ),
        migrations.RemoveField(
            model_name='message',
            name='to_user_status',
        ),
    ]
