# Generated by Django 2.0.1 on 2018-02-08 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20180206_1412'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='to_user',
            new_name='addressee',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='user',
            new_name='sender',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='delete_status',
            new_name='sender_status',
        ),
        migrations.AddField(
            model_name='message',
            name='addressee_status',
            field=models.BooleanField(default=False, verbose_name='收件人删除状态'),
        ),
    ]
