# Generated by Django 2.0.1 on 2018-02-09 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_verificationcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationcode',
            name='code',
            field=models.CharField(max_length=6, unique=True, verbose_name='验证码'),
        ),
        migrations.AlterField(
            model_name='verificationcode',
            name='user',
            field=models.CharField(max_length=20, unique=True, verbose_name='用户帐号'),
        ),
    ]
