# Generated by Django 2.0.1 on 2018-02-11 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_auto_20180209_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationcode',
            name='code',
            field=models.CharField(max_length=200, unique=True, verbose_name='验证码'),
        ),
    ]
